### ISSUE TITLE
Visual-novels section suggestions

### ISSUE THREAD

**Issue by Helmasko** [anotherduckling/Wotaku#10]
- cgprepacks link is faulty
- Nyaa has "R+" next to it but nyaa is SFW
- I recommend f95zone.to for english translated VNs (its more for any english translated porn games but there are a lot of VNs)
- for consistency's sake Nyaa and Sukebei links should be narrowed down, i.e. https://sukebei.nyaa.si/?f=0&c=1_3&q= so that it only shows games.
- maybe a recommendation to search with japanese titles on sukebei/nyaa?

**Comment by anotherduckling** [comment]
@Helmasko pushed the new update. see if everything looks good. for some reason gh pages isnt updating

**Comment by Helmasko** [comment]
F95 requires signup, and if were being really nitpicky GOG also requires signup. Though i do question why a legit store is there.
