### ISSUE TITLE
Add Anime streaming

### ISSUE THREAD

**Issue by 0xkarma** [anotherduckling/Wotaku#22]
Hell Fork,

Please add https://aniro.to to Anime streaming.

**Comment by anotherduckling** [comment]
Sorry, we don't add Zoro scrapers.

**Comment by 0xkarma** [comment]
we don't only scrape zoro, for all the animes we have both the links , zoro and gogo to make each anime reliable.

**Comment by 0xkarma** [comment]
@anotherduckling can we please add it?
