### ISSUE TITLE
Add animemusicquiz.com

### ISSUE THREAD

**Issue by lsahnicne** [anotherduckling/Wotaku#27]
It's a browser game where you guess anime by the opening/ending/insert song. Can be played solo or competitively against others. Various game modes. Supports importing data from various anime list websites to play only the anime from your list.
It also kinda doubles as HUGE anime opening/ending/insert song video library, like animethemes.moe, which you can sort of browse in a roundabout way.
Not sure in which section it would belong.

**Comment by anotherduckling** [comment]
already added
![image](https://github.com/anotherduckling/Wotaku/assets/57977673/32717a41-6456-44ed-9812-de957a98d5e5)

**Comment by anotherduckling** [comment]
https://wotaku.moe/misc#tools

**Comment by lsahnicne** [comment]
Oh, I see. I tried searching by URL "animemusicquiz" rather than title that has the words separated.
