### ISSUE TITLE
Edit ototoy.jp category

### ISSUE THREAD

**Issue by necodess** [anotherduckling/Wotaku#28]
Ototoy.jp provides digital only releases but is listed under "physical"

[#Legal](https://wotaku.moe/websites#legal)

![image](https://github.com/anotherduckling/Wotaku/assets/89935904/9fef8ccc-97de-493c-b5b6-260f0e3eb668)

**Comment by anotherduckling** [comment]
Thanks. I have [fixed](https://github.com/anotherduckling/Wotaku/commit/108def6cdb37fa13556516ae946d70443051b80b) the issue.
