### ISSUE TITLE
Dailyal (MyAnimeList client) playstore link invalid.

### ISSUE THREAD

**Issue by Luffyirl** [anotherduckling/Wotaku#46]
Dailyal was removed from playstore, it now uses a companion app on playstore to download it now and also has a github repo 

companion app - https://play.google.com/store/apps/details?id=io.github.jica98.dailyal_support
github - https://github.com/JICA98/DailyAL

app can run without companion app , the companion app is just downloading dailyal

**Comment by anotherduckling** [comment]
Thanks for the report. I have pushed the updated URL..
