### ISSUE TITLE
suggestion, dead site~

### ISSUE THREAD

**Issue by yugo2911** [anotherduckling/Wotaku#49]
dead~
osu!search 
https://osusearch.com/

(maybe they change site name? or dead.~)
Mangaraw Japan 
https://mangaraw.to/
Mangaraw+ 
https://mangarawplus.co/

maybe add~
osu! batch-beatmap-downloader 
https://github.com/nzbasic/batch-beatmap-downloader

doujinstyle-downloader 
https://github.com/Relepega/doujinstyle-downloader

theindex.moe
https://theindex.moe/

**Comment by anotherduckling** [comment]
Thanks for letting us know
